# Generated by Django 5.2.5 on 2025-09-18 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Яндекс Еда'), (2, 'Почта россии'), (3, 'СДЭК'), (4, 'DHL'), (5, 'ПЭК'), (6, 'ДеловыеЛинии'), (7, 'boxberry')], default=1, verbose_name='Тип')),
                ('key_1', models.CharField(max_length=550, verbose_name='Первый ключ (public_ley)')),
                ('key_2', models.CharField(max_length=550, verbose_name='Второй ключ (secret key)')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('turn_on', models.BooleanField(default=False, verbose_name='Включить')),
            ],
            options={
                'verbose_name': 'Способ доставки',
                'verbose_name_plural': 'Способы доставок',
            },
        ),
    ]
