# Generated by Django 5.2.5 on 2025-09-18 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery', '0001_initial'),
        ('sites', '0002_alter_domain_unique'),
        ('webmain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytype',
            name='setting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webmain.settingsglobale', verbose_name='Настройки'),
        ),
        migrations.AddField(
            model_name='deliverytype',
            name='site',
            field=models.ManyToManyField(to='sites.site', verbose_name='Сайты'),
        ),
    ]
