# Generated by Django 5.2.5 on 2025-09-18 06:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('contacted', 'Связались'), ('qualified', 'Квалифицирован'), ('lost', 'Потерян'), ('converted', 'Конвертирован'), ('at_work', 'В работе'), ('passed', 'Сдан')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('procent', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Процент')),
                ('image', models.FileField(blank=True, null=True, upload_to='lead/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'webp', 'jpeg', 'jpg', 'svg'])], verbose_name='Изображение')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
                ('profit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Прибыль')),
                ('expenditure', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Расход')),
                ('paid_out', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Выплачено')),
                ('swim_out', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='К выплате')),
            ],
            options={
                'verbose_name': 'Лид',
                'verbose_name_plural': 'Лиды',
            },
        ),
        migrations.CreateModel(
            name='Leaddocement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='lead/%Y/%m/%d/', verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.CreateModel(
            name='StatusPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('payout', 'Выплата'), ('replenishment', 'Пополнение')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('type', models.CharField(choices=[('at_work', 'В работе'), ('complite', 'Завершен'), ('pending_review', 'Ожидающий рассмотрения')], max_length=20, verbose_name='Тип')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], default='medium', max_length=10, verbose_name='Приоритет')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('due_date', models.DateTimeField(verbose_name='Срок исполнения')),
                ('notes', models.TextField(blank=True, verbose_name='Комментарий')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Позиция')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('stage', models.CharField(choices=[('prospecting', 'В процесе'), ('proposal', 'Отправленное предложение'), ('negotiation', 'Переговоры'), ('won', 'Сдан'), ('lost', 'Не сдан')], default='prospecting', max_length=20, verbose_name='Этап')),
                ('expected_close_date', models.DateTimeField(blank=True, null=True, verbose_name='Ожидаемая дата закрытия')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Позиция')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='crm.deal', verbose_name='Родительская сделка')),
            ],
            options={
                'verbose_name': 'Сделка',
                'verbose_name_plural': 'Сделки',
                'ordering': ['position'],
            },
        ),
    ]
