# Generated by Django 5.2.5 on 2025-09-18 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0002_initial'),
        ('shop', '0001_initial'),
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationsproducts',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='cart',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site', verbose_name='Сайт'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='categories',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='shop.categories', verbose_name='Родитель'),
        ),
        migrations.AddField(
            model_name='categories',
            name='site',
            field=models.ManyToManyField(blank=True, default='1', to='sites.site', verbose_name='Сайты'),
        ),
        migrations.AddField(
            model_name='comparelist',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site'),
        ),
        migrations.AddField(
            model_name='comparelist',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compare_lists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compareitem',
            name='compare',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.comparelist'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Авторы'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.chat', verbose_name='Чаты'),
        ),
        migrations.AddField(
            model_name='faqsproducts',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='importhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='manufacturers',
            name='assistant',
            field=models.ManyToManyField(related_name='assistant', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи'),
        ),
        migrations.AddField(
            model_name='manufacturers',
            name='categories',
            field=models.ManyToManyField(blank=True, to='shop.categories', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='manufacturers',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='manufacturers',
            name='site',
            field=models.ManyToManyField(to='sites.site', verbose_name='Сайты'),
        ),
        migrations.AddField(
            model_name='manufacturersexpense',
            name='manufacturers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.manufacturers', verbose_name='Магазин'),
        ),
        migrations.AddField(
            model_name='manufacturersexpense',
            name='manufacturersexpense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.manufacturersexpensetype', verbose_name='Расходник'),
        ),
        migrations.AddField(
            model_name='manufacturersincome',
            name='manufacturers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.manufacturers', verbose_name='Магазин'),
        ),
        migrations.AddField(
            model_name='productcomment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='productcommentmedia',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentmedia', to='shop.productcomment'),
        ),
        migrations.AddField(
            model_name='productexpense',
            name='productexpenseposition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.productexpenseposition', verbose_name='Расходник'),
        ),
        migrations.AddField(
            model_name='productexpensepurchase',
            name='manufacturers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.manufacturers', verbose_name='Магазин'),
        ),
        migrations.AddField(
            model_name='productexpensepurchase',
            name='productexpenseposition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productexpenseposition', to='shop.productexpenseposition', verbose_name='Расходник'),
        ),
        migrations.AddField(
            model_name='products',
            name='atribute',
            field=models.ManyToManyField(blank=True, to='shop.atribute', verbose_name='Атрибуты'),
        ),
        migrations.AddField(
            model_name='products',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.brands', verbose_name='Бренд'),
        ),
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.ManyToManyField(to='shop.categories', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='products',
            name='costprice_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.costprice', verbose_name='Цена себестоимости'),
        ),
        migrations.AddField(
            model_name='products',
            name='expenses',
            field=models.ManyToManyField(blank=True, related_name='Расходы', to='shop.productexpense'),
        ),
        migrations.AddField(
            model_name='products',
            name='manufacturers',
            field=models.ManyToManyField(to='shop.manufacturers', verbose_name='Производитель'),
        ),
        migrations.AddField(
            model_name='products',
            name='site',
            field=models.ManyToManyField(to='sites.site', verbose_name='Сайты'),
        ),
        migrations.AddField(
            model_name='productexpense',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.products', verbose_name='Продукт'),
        ),
        migrations.AddField(
            model_name='faqsproducts',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_faq', to='shop.products', verbose_name='Образец Продукта'),
        ),
        migrations.AddField(
            model_name='costprice',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cost_prices', to='shop.products', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.products', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='compareitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='shop.products'),
        ),
        migrations.AddField(
            model_name='categories',
            name='products_rekomendet',
            field=models.ManyToManyField(blank=True, to='shop.products', verbose_name='Товары'),
        ),
        migrations.AddField(
            model_name='applicationsproducts',
            name='products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.products', verbose_name='Образец Продукта'),
        ),
        migrations.AddField(
            model_name='productscloud',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.products', verbose_name='Образец Продукта'),
        ),
        migrations.AddField(
            model_name='productscloud',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='productsgallery',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productsgallery_set', to='shop.products', verbose_name='Образец Продукта'),
        ),
        migrations.AddField(
            model_name='productsprice',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_prices', to='shop.products', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='products',
            name='price_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.productsprice', verbose_name='Цена товара'),
        ),
        migrations.AddField(
            model_name='productspriceold',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_prices_old', to='shop.products', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='products',
            name='price_item_old',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.productspriceold', verbose_name='Старая цена товара'),
        ),
        migrations.AddField(
            model_name='productspriceseller',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_prices_seller', to='shop.products', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='products',
            name='price_item_seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.productspriceseller', verbose_name='Цена продавца'),
        ),
        migrations.AddField(
            model_name='productsvariable',
            name='attribute',
            field=models.ManyToManyField(blank=True, related_name='product_variables', to='shop.atribute', verbose_name='Атрибуты'),
        ),
        migrations.AddField(
            model_name='productsvariable',
            name='costprice_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.costprice', verbose_name='Цена себестоимости'),
        ),
        migrations.AddField(
            model_name='productsvariable',
            name='price_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.productsprice', verbose_name='Цена товара'),
        ),
        migrations.AddField(
            model_name='productsvariable',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.products', verbose_name='Образец Продукта'),
        ),
        migrations.AddField(
            model_name='productsvariable',
            name='site',
            field=models.ManyToManyField(to='sites.site', verbose_name='Сайты'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='advertisement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.productsvariable', verbose_name='Вариация'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shop.products', verbose_name='Продукт'),
        ),
        migrations.AddField(
            model_name='reviewimage',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.reviews'),
        ),
        migrations.AddField(
            model_name='selectedproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.products', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='selectedproduct',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.reviews', verbose_name='Отзыв'),
        ),
        migrations.AddField(
            model_name='selectedproduct',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='selectedproduct',
            name='variety',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.productsvariable', verbose_name='Вариация'),
        ),
        migrations.AddField(
            model_name='productcomment',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='shop.selectedproduct', verbose_name='Ticket'),
        ),
        migrations.AddField(
            model_name='cart',
            name='selectedproduct',
            field=models.ManyToManyField(blank=True, to='shop.selectedproduct', verbose_name='Выбранные Товары'),
        ),
        migrations.AddField(
            model_name='stockavailability',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.products', verbose_name='Образец Продукта'),
        ),
        migrations.AddField(
            model_name='stockavailability',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.storage', verbose_name='Склад'),
        ),
        migrations.AddField(
            model_name='products',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='Тэги', to='shop.tag'),
        ),
        migrations.AddField(
            model_name='productsvariable',
            name='valute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.valute', verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='products',
            name='valute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.valute', verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='importhistory',
            name='valute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.valute', verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='cart',
            name='valute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.valute', verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='variable',
            name='site',
            field=models.ManyToManyField(to='sites.site', verbose_name='Сайты'),
        ),
        migrations.AddField(
            model_name='atribute',
            name='variable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.variable', verbose_name='Вариация'),
        ),
        migrations.AlterUniqueTogether(
            name='comparelist',
            unique_together={('session_key', 'site'), ('user', 'site')},
        ),
        migrations.AlterUniqueTogether(
            name='compareitem',
            unique_together={('compare', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('browser_key', 'site'), ('user', 'site')},
        ),
    ]
