# Generated by Django 4.2.4 on 2025-08-14 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(choices=[(0, 'Сотрудник'), (1, 'Обычный'), (2, 'Юр лицо'), (3, 'Компания')], default=1, verbose_name='Тип')),
                ('name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('site', models.ManyToManyField(blank=True, default='1', to='sites.site', verbose_name='Сайты')),
            ],
            options={
                'verbose_name': 'Документация',
                'verbose_name_plural': 'Документации',
            },
        ),
        migrations.CreateModel(
            name='DocumentationsMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documentations/%Y/%m/%d/')),
                ('documentations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentations', to='documentation.documentations')),
            ],
            options={
                'verbose_name': 'Файл документации',
                'verbose_name_plural': 'Файлы документации',
            },
        ),
    ]
