# Generated by Django 5.2.5 on 2025-09-18 06:10

import ckeditor.fields
import django.core.validators
import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsModeration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(blank=True, null=True, upload_to='settings/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'webp', 'jpeg', 'jpg', 'svg'])], verbose_name='Логотип')),
                ('logo_lg', models.FileField(blank=True, null=True, upload_to='settings/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'webp', 'jpeg', 'jpg', 'svg'])], verbose_name='Дополнительный логотип полный')),
                ('logo_sm', models.FileField(blank=True, null=True, upload_to='settings/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'webp', 'jpeg', 'jpg', 'svg'])], verbose_name='Дополнительный логотип маленький')),
                ('logo_white', models.FileField(blank=True, null=True, upload_to='settings/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'webp', 'jpeg', 'jpg', 'svg'])], verbose_name='Логотип белый')),
                ('logo_white_lg', models.FileField(blank=True, null=True, upload_to='settings/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'webp', 'jpeg', 'jpg', 'svg'])], verbose_name='Дополнительный белый полный')),
                ('logo_white_sm', models.FileField(blank=True, null=True, upload_to='settings/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'webp', 'jpeg', 'jpg', 'svg'])], verbose_name='Дополнительный логотип белый маленький')),
                ('favicon', models.FileField(blank=True, null=True, upload_to='settings/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'webp', 'jpeg', 'jpg', 'svg'])], verbose_name='Фавикон')),
                ('name', models.CharField(blank=True, default='Название сайта', max_length=500, null=True, verbose_name='Название')),
                ('buttom', models.CharField(blank=True, max_length=500, null=True, verbose_name='Кнопка')),
                ('siddebar', models.CharField(blank=True, max_length=500, null=True, verbose_name='Сайдбар')),
                ('types', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('statistic', 'Статистика'), ('groups', 'Группы'), ('employees', 'Сотрудники'), ('clients', 'Клиенты'), ('knowledge_base', 'База знаний'), ('email', 'Email'), ('telephony', 'Телефония'), ('projects', 'Проекты'), ('completed_works', 'Проделанные работы'), ('schedule', 'График'), ('task_manager', 'Задачник'), ('accounting', 'Бухгалтерия'), ('payments', 'Платежи'), ('requests', 'Запросы'), ('household', 'Хоз. часть'), ('lesson', 'Урок'), ('training', 'Обучение'), ('vacancies', 'Вакансии'), ('applications', 'Заявки'), ('warehouses', 'Склады (Магазины)'), ('companies', 'Компании'), ('products', 'Товары'), ('categories', 'Категории'), ('purchases', 'Покупки'), ('complaints', 'Жалобы'), ('reviews', 'Отзывы'), ('comments', 'Комментарии'), ('questions', 'Вопросы'), ('variations', 'Вариации'), ('currency', 'Валюта'), ('support', 'Поддержка'), ('tickets', 'Тикеты'), ('appeal', 'Обращение'), ('domains', 'Домены'), ('loyalty_program', 'Программа лояльности'), ('notifications', 'Уведомления'), ('languages', 'Языки'), ('integrations', 'Интеграции'), ('blog', 'Блог (Новости)'), ('pages', 'Страницы'), ('charity', 'Благотворительность'), ('gallery', 'Галерея'), ('services', 'Услуги'), ('price', 'Прайс'), ('faq', 'ЧаВо'), ('documentation', 'Документация'), ('personal', 'Личные')], default=list, max_length=255, null=True, verbose_name='Доступ')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='ThemesCastegorys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('description', ckeditor.fields.RichTextField(db_index=True, verbose_name='Описание')),
                ('slug', models.SlugField(max_length=140)),
                ('cover', models.FileField(blank=True, null=True, upload_to='themes/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'webp', 'jpeg', 'jpg', 'svg'])], verbose_name='Обложка')),
                ('icon', models.FileField(blank=True, null=True, upload_to='themes/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'webp', 'jpeg', 'jpg', 'svg'])], verbose_name='Иконка')),
                ('image', models.FileField(blank=True, null=True, upload_to='themes/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'webp', 'jpeg', 'jpg', 'svg'])], verbose_name='Картинка')),
                ('publishet', models.BooleanField(default=False, verbose_name='Опубликован')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Категория темы',
                'verbose_name_plural': 'Категории темы',
            },
        ),
        migrations.CreateModel(
            name='Themes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('description', ckeditor.fields.RichTextField(db_index=True, verbose_name='Описание')),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('cover', models.FileField(blank=True, default='default/blogs/cover.png', null=True, upload_to='blogs/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'webp', 'jpeg', 'jpg', 'svg'])], verbose_name='Обложка')),
                ('version', models.CharField(blank=True, max_length=150, null=True, verbose_name='Версия')),
                ('publishet', models.BooleanField(default=False, verbose_name='Опубликован')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления')),
                ('categorys', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='development.themescastegorys', verbose_name='Категория темы')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
            },
        ),
        migrations.CreateModel(
            name='ThemesMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='ticket/%Y/%m/%d/tiket_file/')),
                ('themes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='development.themes', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Файл темы',
                'verbose_name_plural': 'Файлы темы',
            },
        ),
    ]
