# Generated by Django 5.2.5 on 2025-09-18 06:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviews', models.BooleanField(default=False, verbose_name='Оставлен отзыв')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Оплата не прошла'), (2, 'Оплачено')], default=1, verbose_name='Тип оплаты')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Комплектуется'), (2, 'Отправлен')], default=1, verbose_name='Статус')),
                ('offline', models.BooleanField(default=False)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заказа')),
                ('phone_number', models.CharField(db_index=True, max_length=20, verbose_name='Номер телефона')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Имя')),
                ('customer_surname', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('customer_email', models.CharField(max_length=200, verbose_name='Адрес эл почты')),
                ('sflat', models.CharField(blank=True, max_length=200, null=True, verbose_name='Квартира')),
                ('sfloor', models.CharField(blank=True, max_length=200, null=True, verbose_name='Этаж')),
                ('porch', models.CharField(blank=True, max_length=200, null=True, verbose_name='Подьезд')),
                ('user_comment', models.TextField(blank=True, null=True, verbose_name='Комментарий к доставке от пользователя ')),
                ('requires_delivery', models.BooleanField(default=False, verbose_name='Требуется доставка')),
                ('delivery_address', models.TextField(blank=True, null=True, verbose_name='Адрес доставки')),
                ('longitude', models.TextField(blank=True, null=True, verbose_name='Адрес longitude')),
                ('latitude', models.TextField(blank=True, null=True, verbose_name='Адрес latitude')),
                ('city', models.TextField(blank=True, null=True, verbose_name='Адрес Город')),
                ('adress', models.TextField(blank=True, null=True, verbose_name='Адрес Дома')),
                ('amount', models.PositiveSmallIntegerField(default=0, verbose_name='Сумма')),
                ('delivery_price', models.PositiveSmallIntegerField(default=0, verbose_name='Сумма за доставку')),
                ('all_amount', models.PositiveIntegerField(default=0, verbose_name='Общая сумма')),
                ('key', models.CharField(blank=True, max_length=32, unique=True, verbose_name='Ключ')),
                ('purchase_url', models.TextField(blank=True, null=True, verbose_name='Покупка юрл')),
                ('payload', models.TextField(blank=True, null=True, verbose_name='Payload')),
                ('is_payload_set', models.BooleanField(default=False)),
                ('claim_id', models.TextField(blank=True, null=True, verbose_name='claim_id')),
                ('is_claim_id_set', models.BooleanField(default=False, verbose_name='claim_id_statsus')),
                ('mail_send', models.BooleanField(default=False, verbose_name='mail_send')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'ЮКасса'), (1, 'ЮМани'), (2, 'Тинькоф'), (3, 'Gateway'), (4, 'АльфаБанк'), (5, 'СберБанк'), (6, 'ВТБ'), (7, 'СовкомБанк'), (8, 'ПочтаБанк'), (9, 'FreedomPay'), (10, 'PayTR')], default=1, verbose_name='Тип')),
                ('key_1', models.TextField(verbose_name='Первый ключ (public key)')),
                ('key_2', models.CharField(max_length=550, verbose_name='Второй ключ (secret key)')),
                ('shop_key', models.CharField(max_length=550, verbose_name='Ключ магазина (shop key)')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('turn_on', models.BooleanField(default=False, verbose_name='Включить')),
                ('image', models.FileField(blank=True, null=True, upload_to='payment_type/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'webp', 'jpeg', 'jpg', 'svg'])], verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Способ оплаты',
                'verbose_name_plural': 'Способы оплаты',
            },
        ),
        migrations.CreateModel(
            name='PurchasedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Купленный товар',
                'verbose_name_plural': 'Купленные товары',
            },
        ),
    ]
