# Generated by Django 5.2.5 on 2025-09-18 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0001_initial'),
        ('shop', '0001_initial'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='selectedproduct',
            field=models.ManyToManyField(to='shop.selectedproduct', verbose_name='Выбранные Товары'),
        ),
        migrations.AddField(
            model_name='order',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site', verbose_name='Сайты'),
        ),
    ]
