# Generated by Django 5.2.5 on 2025-09-18 06:10

import loyalty.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('code', models.CharField(default=loyalty.models.generate_coupon_code, editable=False, max_length=12, unique=True, verbose_name='Код купона')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='Дата жизни')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Не активирован'), (1, 'Активирован')], default=0, verbose_name='Статус')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Скидка (%)')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма скидки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата активации')),
            ],
            options={
                'verbose_name': 'Купон',
                'verbose_name_plural': 'Купоны',
            },
        ),
        migrations.CreateModel(
            name='PersonalPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активирован')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='Дата жизни')),
                ('Менеджер', models.BooleanField(default=True)),
            ],
        ),
    ]
