# Generated by Django 5.2.5 on 2025-09-18 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loyalty', '0001_initial'),
        ('payment', '0001_initial'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.brands', verbose_name='Бренд'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.categories', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='manufacturers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.manufacturers', verbose_name='Магазин'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.order', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.products', verbose_name='Товар'),
        ),
    ]
