# Generated by Django 5.2.5 on 2025-09-18 06:10

import django.core.validators
import integration_import.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportCsv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveIntegerField(choices=[(1, 'Товары'), (2, 'Категории товаров'), (3, 'Вариации'), (4, 'Производители'), (5, 'Статьи'), (6, 'Категории статей'), (7, 'SEO'), (8, 'Настройки'), (9, 'Баннер')], default=1, verbose_name='Тип')),
                ('create', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.BooleanField(default=False, verbose_name='Статус')),
                ('created_all_elements', models.BooleanField(default=False, verbose_name='Созданы все элементы')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('passed', models.PositiveIntegerField(default=0, verbose_name='Удачных')),
                ('added_element', models.PositiveIntegerField(default=0, verbose_name='Добавлено')),
                ('upload_element', models.PositiveIntegerField(default=0, verbose_name='Обновлено')),
                ('file', models.FileField(blank=True, null=True, upload_to=integration_import.models.get_xlsx_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv', 'xlsx'])], verbose_name='файл')),
                ('pause_status', models.BooleanField(default=False, verbose_name='Статус Паузы')),
                ('last_object', models.PositiveIntegerField(blank=True, null=True, verbose_name='Последний обьект до паузы')),
            ],
            options={
                'verbose_name': 'Импорт',
                'verbose_name_plural': 'Импорты',
            },
        ),
        migrations.CreateModel(
            name='ImportCsvElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=integration_import.models.get_upload_to)),
                ('status', models.BooleanField(default=False)),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('passed', models.PositiveIntegerField(default=0, verbose_name='Удачных')),
                ('added_element', models.PositiveIntegerField(default=0, verbose_name='Добавленных')),
                ('upload_element', models.PositiveIntegerField(default=0, verbose_name='Обновленных')),
            ],
            options={
                'verbose_name': 'Импорт Эл',
                'verbose_name_plural': 'Импорты Эл',
            },
        ),
        migrations.CreateModel(
            name='UploadFromDiskImportCsv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveIntegerField(choices=[(1, 'Товары'), (2, 'Категории товаров'), (3, 'Вариации'), (4, 'Производители'), (5, 'Статьи'), (6, 'Категории статей'), (7, 'SEO'), (8, 'Настройки'), (9, 'Баннер')], default=1, verbose_name='Тип')),
                ('link', models.TextField(blank=True, null=True, verbose_name='Ссылка на диск')),
                ('imagelink', models.TextField(blank=True, null=True, verbose_name='Ссылка на папку с картинками')),
                ('activate', models.BooleanField(default=False, verbose_name='Активирован')),
                ('last_attempt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Импорт С Я.Диска',
                'verbose_name_plural': 'Импорт С Я.Диска',
            },
        ),
        migrations.CreateModel(
            name='YandexDiskIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField(blank=True, null=True, verbose_name='Ключ')),
                ('activate', models.BooleanField(default=False, verbose_name='Активирован')),
            ],
            options={
                'verbose_name': 'Интеграция с Я.Диском',
                'verbose_name_plural': 'Интеграция с Я.Диском',
            },
        ),
    ]
