# Generated by Django 5.2.5 on 2025-09-18 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integration_import', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='importcsv',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='importcsvelement',
            name='import_csv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='integration_import.importcsv'),
        ),
        migrations.AddField(
            model_name='importcsv',
            name='last_element',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='integration_import.importcsvelement', verbose_name='Последний Элемент до Паузы'),
        ),
        migrations.AddField(
            model_name='importcsv',
            name='uploadfromdisk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='integration_import.uploadfromdiskimportcsv', verbose_name='Загрузка'),
        ),
    ]
