# Generated by Django 5.2.5 on 2025-09-18 06:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Групповой'), (2, 'Личные')], default=1, verbose_name='Тип')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата последнего обновления')),
                ('object_id', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Чат',
                'verbose_name_plural': 'Чаты',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('status', models.SmallIntegerField(choices=[(0, 'Отправлено'), (1, 'Прочитано')], default=1, verbose_name='Статус')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('content', models.TextField(verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='ChatMessageMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='chat_message_media_upload_to/%Y/%m/%d/')),
                ('filename', models.CharField(blank=True, max_length=250, null=True, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Файл сообщений чата',
                'verbose_name_plural': 'Файлы сообщений чата',
            },
        ),
    ]
