# Generated by Django 5.2.5 on 2025-09-18 06:10

import ckeditor.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time', models.PositiveIntegerField(default=0, verbose_name='Длительность')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=11, verbose_name='Цена')),
                ('quantity_files', models.PositiveIntegerField(default=0, verbose_name='Количество файлов')),
                ('quantity_tests', models.PositiveIntegerField(default=0, verbose_name='Количество тестов')),
                ('quantity_video', models.PositiveIntegerField(default=0, verbose_name='Количество видео')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('cover', models.FileField(blank=True, default='default/blogs/cover.png', null=True, upload_to='lesson/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'webp', 'jpeg', 'jpg', 'svg'])], verbose_name='Обложка')),
                ('image', models.FileField(blank=True, default='default/blogs/cover.png', null=True, upload_to='lesson/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'webp', 'jpeg', 'jpg', 'svg'])], verbose_name='Изображение')),
                ('description', ckeditor.fields.RichTextField(db_index=True, verbose_name='Описание')),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('previev', models.FileField(blank=True, default='default/imagegallery/imagegellery_images.png', null=True, upload_to='pages/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'webp', 'jpeg', 'jpg', 'svg'])], verbose_name='Превью')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Мета-заголовок')),
                ('metadescription', models.CharField(blank=True, max_length=255, null=True, verbose_name='Мета-описание')),
                ('propertytitle', models.CharField(blank=True, max_length=150, null=True, verbose_name='Мета-заголовок ссылки')),
                ('propertydescription', models.CharField(blank=True, max_length=255, null=True, verbose_name='Мета-описание ссылки')),
                ('public', models.BooleanField(default=False, verbose_name='Доступен всем')),
                ('publishet', models.BooleanField(default=False, verbose_name='Опубликован')),
                ('resources', models.TextField(default='[]', verbose_name='Ресурсы')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
        migrations.CreateModel(
            name='LessonMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, upload_to='lesson/')),
                ('new_file', models.FileField(blank=True, editable=False, null=True, upload_to='')),
                ('original_filename', models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Оригинальное имя файла')),
                ('temp_file_id', models.CharField(blank=True, editable=False, max_length=64, null=True, verbose_name='ID временного файла')),
                ('create', models.DateTimeField(auto_now_add=True, null=True)),
                ('uploaded_size', models.PositiveIntegerField(blank=True, default=0, editable=False, null=True)),
                ('size', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('active', models.BooleanField(default=False, verbose_name='Загружено')),
            ],
            options={
                'verbose_name': 'Материал урока',
                'verbose_name_plural': 'Материалы урока',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagetype', models.PositiveSmallIntegerField(choices=[(1, 'Blue'), (2, 'Gray Dark'), (3, 'Green'), (4, 'Cyan'), (5, 'Yellow'), (6, 'Red'), (7, 'Dark')], default=1, verbose_name='Тип')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создание')),
                ('data_start', models.DateField(blank=True, null=True, verbose_name='Дата начало')),
                ('data_end', models.DateField(blank=True, null=True, verbose_name='Дата конца')),
                ('time_start', models.TimeField(blank=True, null=True, verbose_name='Время начало')),
                ('time_end', models.TimeField(blank=True, null=True, verbose_name='Время конца')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('description', models.TextField(db_index=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'График',
                'verbose_name_plural': 'Графики',
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Оценка')),
                ('total_questions', models.PositiveIntegerField(default=0, verbose_name='Общее количество вопросов')),
                ('correct_answers', models.PositiveIntegerField(default=0, verbose_name='Правильные ответы')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата завершения')),
                ('resources', models.TextField(default='[]', verbose_name='Ресурсы')),
            ],
            options={
                'verbose_name': 'Результат тестирования',
                'verbose_name_plural': 'Результаты тестирования',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_schedule', models.CharField(choices=[('1', 'Полный рабочий день'), ('2', 'Неполный рабочий день'), ('3', 'Удаленная работа'), ('4', 'Сменный график')], default='1', max_length=20, verbose_name='График работы')),
                ('title', models.CharField(max_length=255, verbose_name='Название вакансии')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Название вакансии')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Название вакансии')),
                ('title_tg', models.CharField(max_length=255, null=True, verbose_name='Название вакансии')),
                ('title_tr', models.CharField(max_length=255, null=True, verbose_name='Название вакансии')),
                ('title_kk', models.CharField(max_length=255, null=True, verbose_name='Название вакансии')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='Название вакансии')),
                ('description', models.TextField(verbose_name='Описание вакансии')),
                ('description_ru', models.TextField(null=True, verbose_name='Описание вакансии')),
                ('description_en', models.TextField(null=True, verbose_name='Описание вакансии')),
                ('description_tg', models.TextField(null=True, verbose_name='Описание вакансии')),
                ('description_tr', models.TextField(null=True, verbose_name='Описание вакансии')),
                ('description_kk', models.TextField(null=True, verbose_name='Описание вакансии')),
                ('description_uz', models.TextField(null=True, verbose_name='Описание вакансии')),
                ('requirements', models.TextField(verbose_name='Требования к кандидату')),
                ('requirements_ru', models.TextField(null=True, verbose_name='Требования к кандидату')),
                ('requirements_en', models.TextField(null=True, verbose_name='Требования к кандидату')),
                ('requirements_tg', models.TextField(null=True, verbose_name='Требования к кандидату')),
                ('requirements_tr', models.TextField(null=True, verbose_name='Требования к кандидату')),
                ('requirements_kk', models.TextField(null=True, verbose_name='Требования к кандидату')),
                ('requirements_uz', models.TextField(null=True, verbose_name='Требования к кандидату')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Заработная плата')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Местоположение')),
                ('location_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Местоположение')),
                ('location_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Местоположение')),
                ('location_tg', models.CharField(blank=True, max_length=255, null=True, verbose_name='Местоположение')),
                ('location_tr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Местоположение')),
                ('location_kk', models.CharField(blank=True, max_length=255, null=True, verbose_name='Местоположение')),
                ('location_uz', models.CharField(blank=True, max_length=255, null=True, verbose_name='Местоположение')),
                ('posted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата размещения вакансии')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность вакансии')),
                ('image', models.FileField(blank=True, null=True, upload_to='vacancy/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'webp', 'jpeg', 'jpg', 'svg'])], verbose_name='Картинка')),
                ('slug', models.SlugField(max_length=140)),
                ('create', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
        migrations.CreateModel(
            name='VacancyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Сообщение')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/%Y/%m/%d/', verbose_name='Резюме')),
                ('create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkShift',
            fields=[
                ('date_start', models.DateField(blank=True, null=True, verbose_name='Дата выхода на смену')),
                ('time_start', models.TimeField(blank=True, null=True, verbose_name='Время выхода на смену')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='Дата ухода со смены')),
                ('time_end', models.TimeField(blank=True, null=True, verbose_name='Время ухода со смены')),
                ('photo_accept_place', models.ImageField(blank=True, null=True, upload_to='work_shifts/accept/', verbose_name='Фото принятия рабочего места')),
                ('photo_entry_place', models.ImageField(blank=True, null=True, upload_to='work_shifts/entry/', verbose_name='Фото выхода на рабочее место')),
                ('selfie_entry', models.ImageField(blank=True, null=True, upload_to='work_shifts/selfies/', verbose_name='Собственное фото (приход)')),
                ('video_entry', models.FileField(blank=True, null=True, upload_to='work_shifts/video_entry/', verbose_name='Видео фиксации прихода')),
                ('photo_handover_place', models.ImageField(blank=True, null=True, upload_to='work_shifts/handover/', verbose_name='Фото сдачи рабочего места')),
                ('photo_exit_place', models.ImageField(blank=True, null=True, upload_to='work_shifts/exit/', verbose_name='Фото ухода с рабочего места')),
                ('selfie_exit', models.ImageField(blank=True, null=True, upload_to='work_shifts/selfies/', verbose_name='Собственное фото (уход)')),
                ('video_exit', models.FileField(blank=True, null=True, upload_to='work_shifts/video_exit/', verbose_name='Видео фиксации ухода')),
                ('work_status', models.CharField(choices=[('1', 'Выход'), ('2', 'Уход')], default='1', max_length=20, verbose_name='Тип')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Выход/уход со смены',
                'verbose_name_plural': 'Выходы/уходы со смены',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HRChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100, verbose_name='Изменённое поле')),
                ('old_value', models.TextField(verbose_name='Старое значения')),
                ('new_value', models.TextField(verbose_name='Новое значения')),
                ('time_change', models.DateTimeField(auto_now_add=True, verbose_name='Время изменения')),
                ('object_id', models.CharField(max_length=100)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Изменение',
                'verbose_name_plural': 'Изменении',
            },
        ),
    ]
