# Generated by Django 5.2.5 on 2025-09-18 06:10

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('CustomerID', models.AutoField(primary_key=True, serialize=False, verbose_name='ID бонуса')),
                ('Name', models.CharField(db_index=True, max_length=255, verbose_name='Название')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма')),
                ('reason', models.TextField(verbose_name='Причина')),
            ],
            options={
                'verbose_name': 'Бонус',
                'verbose_name_plural': 'Бонусы',
            },
        ),
        migrations.CreateModel(
            name='Change',
            fields=[
                ('CustomerID', models.AutoField(primary_key=True, serialize=False, verbose_name='ID смены')),
                ('Name', models.CharField(db_index=True, max_length=255, verbose_name='Название смены')),
                ('Schedule', models.CharField(db_index=True, max_length=255, verbose_name='График')),
            ],
            options={
                'verbose_name': 'Смена',
                'verbose_name_plural': 'Смены',
                'ordering': ['Name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('CustomerID', models.AutoField(primary_key=True, serialize=False, verbose_name='ID отдела')),
                ('Name', models.CharField(db_index=True, max_length=255, verbose_name='Название отдела')),
                ('Description', models.TextField(blank=True, verbose_name='Описание отдела')),
                ('Chart', models.TextField(blank=True, null=True, verbose_name='График работы')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
                'ordering': ['Name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hire_date', models.DateField(auto_now_add=True, verbose_name='Дата приема на работу')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeePosition',
            fields=[
                ('CustomerID', models.AutoField(primary_key=True, serialize=False, verbose_name='ID позиции')),
                ('Name', models.CharField(max_length=255, unique=True, verbose_name='Название должности')),
                ('Description', models.TextField(blank=True, verbose_name='Описание')),
                ('Salary', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Оклад')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должность',
            },
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('CustomerID', models.AutoField(primary_key=True, serialize=False, verbose_name='ID расхода')),
                ('Name', models.CharField(db_index=True, max_length=255, verbose_name='Название расхода')),
                ('Description', models.TextField(blank=True, verbose_name='Описание')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма')),
                ('date', models.DateField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Расход',
                'verbose_name_plural': 'Расходы',
            },
        ),
        migrations.CreateModel(
            name='MonthlyKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('1', 'Январь'), ('2', 'Февраль'), ('3', 'Март'), ('4', 'Апрель'), ('5', 'Май'), ('6', 'Июнь'), ('7', 'Июль'), ('8', 'Август'), ('9', 'Сентябрь'), ('10', 'Октябрь'), ('11', 'Ноябрь'), ('12', 'Декабрь')], max_length=2, verbose_name='Месяц')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='Дата выполнения')),
                ('completed', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Подтверждено')),
            ],
            options={
                'verbose_name': 'Ежемесячный KPI',
                'verbose_name_plural': 'Ежемесячные KPI',
            },
        ),
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('CustomerID', models.AutoField(primary_key=True, serialize=False, verbose_name='ID штрафа')),
                ('Name', models.CharField(db_index=True, max_length=255, verbose_name='Название')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма')),
                ('reason', models.TextField(verbose_name='Причина')),
            ],
            options={
                'verbose_name': 'Штраф',
                'verbose_name_plural': 'Штрафы',
            },
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('CustomerID', models.AutoField(primary_key=True, serialize=False, verbose_name='ID бонуса')),
                ('Name', models.CharField(db_index=True, max_length=255, verbose_name='Название')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма')),
                ('reason', models.TextField(verbose_name='Причина')),
            ],
            options={
                'verbose_name': 'Премия',
                'verbose_name_plural': 'Премии',
            },
        ),
    ]
