# Generated by Django 5.2.5 on 2025-09-18 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kpi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='Guide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments_guided', to=settings.AUTH_USER_MODEL, verbose_name='Руководитель'),
        ),
        migrations.AddField(
            model_name='department',
            name='Staff',
            field=models.ManyToManyField(blank=True, related_name='departments_worked', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудники'),
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='kpi.department', verbose_name='Отдел'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='employeeposition',
            name='Bonuses',
            field=models.ManyToManyField(blank=True, related_name='employee_positions', to='kpi.bonus', verbose_name='Бонусы'),
        ),
        migrations.AddField(
            model_name='employeeposition',
            name='Change',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='kpi.change', verbose_name='Смена'),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kpi.employeeposition', verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='expenses',
            name='Department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_expenses', to='kpi.department', verbose_name='Отдел'),
        ),
        migrations.AddField(
            model_name='expenses',
            name='User',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_created', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='monthlykpi',
            name='bonus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kpi.bonus', verbose_name='Бонус'),
        ),
        migrations.AddField(
            model_name='monthlykpi',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_kpis', to='kpi.employee', verbose_name='Сотрудник'),
        ),
        migrations.AddField(
            model_name='monthlykpi',
            name='penalty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kpi.penalty', verbose_name='Штраф'),
        ),
        migrations.AddField(
            model_name='employeeposition',
            name='Penalties',
            field=models.ManyToManyField(blank=True, related_name='employee_positions', to='kpi.penalty', verbose_name='Штрафы'),
        ),
        migrations.AddField(
            model_name='monthlykpi',
            name='prize',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kpi.prize', verbose_name='Премия'),
        ),
        migrations.AddField(
            model_name='employeeposition',
            name='Prizes',
            field=models.ManyToManyField(blank=True, related_name='employee_positions', to='kpi.prize', verbose_name='Премии'),
        ),
    ]
