# Generated by Django 5.2.5 on 2025-09-18 06:10

import django.core.validators
import multiselectfield.db.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AggregatedExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('data', models.DateTimeField(blank=True, null=True, verbose_name='Дата')),
                ('revenue_by_products', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Выручка по товарам')),
                ('expenses_by_products', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Расходы по товарам')),
                ('expenses_by_store', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Расходы магазина')),
                ('expenses_by_employee', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Расходы по Сотрудникам')),
                ('income', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Доходы')),
            ],
        ),
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Заявка'), (2, 'Покупка'), (3, 'Партнерство'), (4, 'Сотрудничество')], default=1, verbose_name='Тип')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create', models.DateTimeField(auto_now=True, null=True)),
                ('email', models.CharField(blank=True, max_length=500, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=500, null=True, verbose_name='Телефон')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('company_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Название компании')),
                ('company_inn', models.CharField(blank=True, max_length=500, null=True, verbose_name='ИНН организации или ИП')),
                ('company_director', models.CharField(blank=True, max_length=500, null=True, verbose_name='ФИО директора')),
                ('company_adress', models.CharField(blank=True, max_length=500, null=True, verbose_name='Адрес')),
                ('company_sku', models.CharField(blank=True, max_length=500, null=True, verbose_name='Количество товаров SKU в вашем каталоге')),
                ('company_description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Запрос на сотрудничество',
                'verbose_name_plural': 'Запросы на сотрудничество',
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('inventory_number', models.CharField(max_length=100, unique=True, verbose_name='Инвентарный номер')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Дата покупки')),
                ('warranty_expiration', models.DateField(blank=True, null=True, verbose_name='Окончание гарантии')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Расположение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Имущество компании',
                'verbose_name_plural': 'Имущества компании',
            },
        ),
        migrations.CreateModel(
            name='AssetUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken_at', models.DateTimeField(verbose_name='Дата выдачи')),
                ('returned_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата возврата')),
                ('purpose', models.CharField(blank=True, max_length=255, verbose_name='Цель использования')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'История использования',
                'verbose_name_plural': 'Истории использований',
            },
        ),
        migrations.CreateModel(
            name='Collaborations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Имя')),
                ('email', models.CharField(blank=True, max_length=500, null=True, verbose_name='Электронная почта')),
                ('subject', models.CharField(blank=True, max_length=500, null=True, verbose_name='Обьект сотрудничества')),
                ('phone', models.CharField(blank=True, max_length=500, null=True, verbose_name='Номер телефона')),
                ('message', models.TextField(verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('types', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Статистика', [('statistic_generate', 'Генерация'), ('statistic_view', 'Просмотр')]), ('Группы', [('groups_list', 'Список'), ('groups_create', 'Создание'), ('groups_edit', 'Редактирование'), ('groups_delete', 'Удаление')]), ('Сотрудники', [('employees_list', 'Список'), ('employees_create', 'Создание'), ('employees_edit', 'Редактирование'), ('employees_delete', 'Удаление')]), ('Клиенты', [('clients_list', 'Список'), ('clients_create', 'Создание'), ('clients_edit', 'Редактирование'), ('clients_delete', 'Удаление')]), ('База знаний', [('knowledge_list', 'Список'), ('knowledge_create', 'Создание'), ('knowledge_edit', 'Редактирование'), ('knowledge_delete', 'Удаление')]), ('Email', [('email_send', 'Отправка'), ('email_list', 'Список')]), ('Телефония', [('telephony_list', 'Список'), ('telephony_call', 'Звонок')]), ('Проекты', [('projects_list', 'Список'), ('projects_create', 'Создание'), ('projects_edit', 'Редактирование'), ('projects_delete', 'Удаление')]), ('Проделаные работы', [('works_list', 'Список')]), ('График', [('schedule_view', 'Просмотр'), ('schedule_edit', 'Редактирование')]), ('Задачник', [('tasks_list', 'Список'), ('tasks_create', 'Создание'), ('tasks_edit', 'Редактирование'), ('tasks_delete', 'Удаление')]), ('Бухгалтерия', [('accounting_view', 'Просмотр')]), ('Платежи', [('payments_list', 'Список'), ('payments_create', 'Создание')]), ('Запросы', [('requests_list', 'Список')]), ('Хоз.часть', [('admin_part_view', 'Просмотр')]), ('Урок', [('lesson_list', 'Список')]), ('Обучение', [('training_list', 'Список')]), ('Вакансии', [('vacancies_list', 'Список'), ('vacancies_create', 'Создание'), ('vacancies_edit', 'Редактирование'), ('vacancies_delete', 'Удаление')]), ('Заявки', [('applications_list', 'Список'), ('applications_create', 'Создание')]), ('Склады (Магазины)', [('storages_list', 'Список'), ('storages_create', 'Создание'), ('storages_edit', 'Редактирование'), ('storages_delete', 'Удаление')]), ('Компании', [('companies_list', 'Список'), ('companies_create', 'Создание')]), ('Товары', [('products_list', 'Список'), ('products_create', 'Создание'), ('products_edit', 'Редактирование'), ('products_delete', 'Удаление')]), ('Категории', [('categories_list', 'Список'), ('categories_create', 'Создание')]), ('Покупки', [('purchases_list', 'Список')]), ('Жалобы', [('complaints_list', 'Список')]), ('Отзывы', [('reviews_list', 'Список')]), ('Комментарии', [('comments_list', 'Список')]), ('Вопросы', [('questions_list', 'Список')]), ('Вариации', [('variations_list', 'Список')]), ('Валюта', [('currency_list', 'Список')]), ('Поддержка', [('support_list', 'Список')]), ('Тикеты', [('tickets_list', 'Список')]), ('Обращение', [('requests_view', 'Просмотр')]), ('Домены', [('domains_list', 'Список'), ('domains_create', 'Создание')]), ('Програма лояльности', [('loyalty_list', 'Список')]), ('Уведомления', [('notifications_list', 'Список')]), ('Языки', [('languages_list', 'Список')]), ('Интеграции', [('integrations_list', 'Список')]), ('Блог (Новости)', [('blog_list', 'Список')]), ('Страницы', [('pages_list', 'Список')]), ('Благотворительность', [('charity_list', 'Список')]), ('Галерея', [('gallery_list', 'Список')]), ('Услуги', [('services_list', 'Список')]), ('Прайс', [('price_list', 'Список')]), ('ЧаВо', [('faq_list', 'Список')]), ('Документация', [('docs_list', 'Список')]), ('Личные', [('personal_view', 'Просмотр')]), ('Профиль', [('profile_view', 'Просмотр')]), ('Начисления', [('charges_list', 'Список')])], default=list, max_length=255, null=True, verbose_name='Доступ')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(editable=False)),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата обслуживания')),
                ('performed_by', models.CharField(max_length=255, verbose_name='Выполнил')),
                ('description', models.TextField(verbose_name='Описание работ')),
                ('next_due_date', models.DateField(blank=True, null=True, verbose_name='Следующее ТО')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Техническое обслуживание',
                'verbose_name_plural': 'Технические обслуживания',
            },
        ),
        migrations.CreateModel(
            name='Notificationgroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Созданно')),
                ('publication', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('object_id', models.CharField(blank=True, max_length=500, null=True, verbose_name='Уникальный номер')),
                ('message', models.TextField()),
                ('slug', models.TextField(editable=False)),
                ('email', models.TextField(blank=True, max_length=500, null=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Груповое уведомление',
                'verbose_name_plural': 'Груповые уведомления',
            },
        ),
        migrations.CreateModel(
            name='ReklamBanner',
            fields=[
                ('types', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('В категории', [('categorys_gorizont', 'Горизонтальные'), ('categorys_vertikal', 'Вертикальные')]), ('Каталог', [('catalog_gorizont', 'Горизонтальные'), ('catalog_vertikal', 'Вертикальные')])], default=list, max_length=255, null=True, verbose_name='Типы')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.FileField(blank=True, null=True, upload_to='product/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'webp', 'jpeg', 'jpg', 'svg'])], verbose_name='Изображение')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('link_name', models.CharField(max_length=150, verbose_name='Название ссылки')),
                ('link', models.CharField(max_length=150, verbose_name='Ссылка')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Рекламный баннер',
                'verbose_name_plural': 'Рекламные баннеры',
            },
        ),
        migrations.CreateModel(
            name='Stopwords',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='Стоп слова')),
            ],
            options={
                'verbose_name': 'Стоп слово',
                'verbose_name_plural': 'Стоп слова',
            },
        ),
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=500, null=True, unique=True, verbose_name='Email')),
                ('create', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Подписки',
                'verbose_name_plural': 'Подписки',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.SmallIntegerField(choices=[(0, 'Новое'), (1, 'Обратная связь'), (2, 'В процессе'), (3, 'Решенный'), (4, 'Закрытый')], default=0, verbose_name='Статус')),
                ('themas', models.TextField(verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Тикет',
                'verbose_name_plural': 'Тикеты',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, 'Заказчик'), (1, 'Поддержка')], default=1, editable=False, verbose_name='Статус')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('content', models.TextField(verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Комментарий тикета',
                'verbose_name_plural': 'Комментарии тикета',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TicketCommentMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='ticket/%Y/%m/%d/tiket_file/')),
            ],
            options={
                'verbose_name': 'Файл комментария тикета',
                'verbose_name_plural': 'Файлы комментариев тикета',
            },
        ),
        migrations.CreateModel(
            name='ViewDayPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now=True, null=True)),
                ('jsoninformation', models.TextField()),
            ],
            options={
                'verbose_name': 'Просмотры за день',
                'verbose_name_plural': 'Просмотры за дни',
            },
        ),
        migrations.CreateModel(
            name='ViewPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now=True, null=True)),
                ('ip', models.CharField(blank=True, max_length=15, null=True, verbose_name='IP Адрес')),
                ('browser', models.CharField(blank=True, max_length=150, null=True, verbose_name='Браузер')),
                ('operationsistem', models.CharField(blank=True, max_length=150, null=True, verbose_name='Операционая система')),
                ('region', models.CharField(blank=True, max_length=150, null=True, verbose_name='Регион')),
                ('link', models.CharField(blank=True, max_length=150, null=True, verbose_name='Ссылка')),
                ('object_id', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Просмотр страницы',
                'verbose_name_plural': 'Просмотры страниц',
            },
        ),
    ]
