# Generated by Django 5.2.5 on 2025-09-18 06:10

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields
import useraccount.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('shop', '0001_initial'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('status', models.BooleanField(default=False, verbose_name='Статус')),
                ('type', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Сотрудник'), (1, 'Обычный'), (2, 'Юр лицо'), (3, 'Компания'), (4, 'Клиент'), (5, 'Известный клиент')], default=1, null=True, verbose_name='Тип пользователя')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, max_length=500, null=True, unique=True, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('avatar', models.FileField(blank=True, default='default/user-nophoto.png', null=True, upload_to=useraccount.models.get_user_dir, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'webp', 'jpeg', 'jpg', 'svg'])], verbose_name='Аватар')),
                ('device_token', models.TextField(blank=True, null=True, verbose_name='FCM токен устройства')),
                ('gender', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Мужской'), (2, 'Женский')], default=1, null=True, verbose_name='Пол')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Город')),
                ('adresses', models.TextField(blank=True, default='[]', null=True, verbose_name='Адреса')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('online', models.BooleanField(default=False, verbose_name='Онлайн')),
                ('blocked', models.BooleanField(default=False, verbose_name='Заблокирован')),
                ('deleted', models.BooleanField(default=False, verbose_name='Удален')),
                ('earned', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Заработано')),
                ('balance', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Баланс')),
                ('frozen', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Замороженный баланс')),
                ('point', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Баллы')),
                ('referral_code', models.CharField(blank=True, default=useraccount.models.generate_random_code, max_length=100, null=True, verbose_name='Личный код')),
                ('referrale_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Личный код')),
                ('passport_issued_by_whom', models.TextField(blank=True, null=True, verbose_name='Кем выдан')),
                ('passport_date_of_issue', models.DateField(blank=True, null=True, verbose_name='Дата выдачи')),
                ('passport_the_sub_division_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Код подрозделения')),
                ('passport_series_and_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Серия и номер')),
                ('passport_place_of_birth', models.TextField(blank=True, null=True, verbose_name='Место рождения')),
                ('passport_registration', models.TextField(blank=True, null=True, verbose_name='Прописка')),
                ('passport_image_1', models.FileField(blank=True, default='default/user-nophoto.png', null=True, upload_to=useraccount.models.get_user_dir, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'webp', 'jpeg', 'jpg', 'svg'])], verbose_name='Лицевая часть')),
                ('passport_image_2', models.FileField(blank=True, default='default/user-nophoto.png', null=True, upload_to=useraccount.models.get_user_dir, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'webp', 'jpeg', 'jpg', 'svg'])], verbose_name='Место прописки')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название организации')),
                ('company_director', models.CharField(blank=True, max_length=100, null=True, verbose_name='Руководитель')),
                ('company_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Юридический адрес')),
                ('company_nalogovaya', models.CharField(blank=True, max_length=100, null=True, verbose_name='Налоговый орган')),
                ('company_ogrn', models.CharField(blank=True, max_length=100, null=True, verbose_name='ОГРН')),
                ('company_inn', models.CharField(blank=True, max_length=100, null=True, verbose_name='ИНН')),
                ('company_kpp', models.CharField(blank=True, max_length=100, null=True, verbose_name='КПП')),
                ('company_data_registration', models.DateField(blank=True, null=True, verbose_name='Дата регистрации')),
                ('company_type_activity', models.TextField(blank=True, null=True, verbose_name='Основной вид деятельности')),
                ('bookmark', models.ManyToManyField(blank=True, null=True, to='shop.products', verbose_name='Закладки')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('manufacturers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.manufacturers', verbose_name='Магазин')),
                ('manufacturers_subscriber', models.ManyToManyField(related_name='subscriber', to='shop.manufacturers', verbose_name='Подписки')),
                ('price_reduction', models.ManyToManyField(blank=True, null=True, related_name='price_reduction', to='shop.products', verbose_name='Закладки')),
                ('referral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('site', models.ManyToManyField(blank=True, default='1', to='sites.site', verbose_name='Сайты')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Bookmarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='По умолчанию', max_length=100, null=True, verbose_name='Название')),
                ('informationjon', models.TextField(help_text='Образец: [{"type": products, "id": [123, 1231edf, 4534fvdvdf]}]', verbose_name='Информация')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Закладка',
                'verbose_name_plural': 'Закладки',
            },
        ),
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.CharField(max_length=19, verbose_name='Карта')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления карты')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Активная'), (2, 'Не активная')], default=2, verbose_name='Статус')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardowner', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Банковская карта',
                'verbose_name_plural': 'Банковские карты',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('director', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Руководитель')),
                ('users', models.ManyToManyField(blank=True, related_name='personalcompany', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'Общее'), (1, 'Регистрация'), (2, 'Покупка'), (3, 'Сбросить пароль'), (4, 'Поддержка')], default=0, verbose_name='Тип')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Не прочитан'), (2, 'Прочитан')], default=1, verbose_name='Статус')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время отправки')),
                ('title', models.TextField(blank=True, null=True, verbose_name='Заголовок')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Сообщение')),
                ('image', models.FileField(blank=True, null=True, upload_to=useraccount.models.get_user_dir, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'webp', 'jpeg', 'jpg', 'svg'])], verbose_name='Изображение')),
                ('sent', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(blank=True, limit_choices_to={'model__in': ('blogs', 'pages', 'categorysblogs', 'tagsblogs')}, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомление',
            },
        ),
        migrations.CreateModel(
            name='PersonalCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.CharField(max_length=19, verbose_name='Карта')),
                ('discount', models.CharField(max_length=19, verbose_name='Скидка')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления карты')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Активная'), (2, 'Не активная')], default=2, verbose_name='Статус')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Стандарт'), (2, 'Професиональная'), (3, 'Вип')], default=1, verbose_name='Тип')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Личная карта',
                'verbose_name_plural': 'Личные карты',
            },
        ),
        migrations.CreateModel(
            name='PersonalGroups',
            fields=[
                ('types', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Номера телефонов', [('phone_default', 'Номер телефона по умолчанию'), ('phone', 'Остальные номера телефонов')]), ('Электроная почта', [('email_default', 'Почта по умолчанию'), ('email', 'Остальные почты')])], default=list, max_length=255, null=True, verbose_name='Доступ')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(editable=False)),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useraccount.company', verbose_name='Руководитель')),
                ('site', models.ManyToManyField(blank=True, default='1', to='sites.site', verbose_name='Сайты')),
                ('users', models.ManyToManyField(blank=True, related_name='grouppersonal', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, null=True, verbose_name='Сумма')),
                ('type_payment', models.SmallIntegerField(choices=[(0, 'Пополнение'), (1, 'Списание')], default=0, verbose_name='Пополнение/Списание')),
                ('type', models.SmallIntegerField(choices=[(0, 'Деньги'), (1, 'Баллы')], default=0, verbose_name='Пополнение/Списание')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('manufacturers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.manufacturers', verbose_name='Магазин')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Выплата',
                'verbose_name_plural': 'Выплаты',
            },
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('query', models.CharField(db_index=True, max_length=255)),
                ('count', models.PositiveIntegerField(default=0)),
                ('last_searched', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['-last_searched'], name='useraccount_last_se_874870_idx'), models.Index(fields=['query'], name='useraccount_query_60d1d4_idx')],
                'unique_together': {('session_key', 'query'), ('user', 'query')},
            },
        ),
    ]
